-- =========================================================
-- 14 MISCELLANEOUS MYSQL COMMANDS
-- =========================================================

-- Version
SELECT VERSION();

-- Current database
SELECT DATABASE();

-- Current user
SELECT USER();

-- Show server status
SHOW STATUS;

-- Show system variables
SHOW VARIABLES;

-- Show storage engines
SHOW ENGINES;

-- Show character sets
SHOW CHARACTER SET;

-- Show table status
USE sql_learning;
SHOW TABLE STATUS;

-- Explain a SELECT query
EXPLAIN SELECT *
FROM students
WHERE city = 'Bengaluru';

-- More detailed optimizer output in MySQL 8+
EXPLAIN ANALYZE
SELECT *
FROM students
WHERE city = 'Bengaluru';

-- Show warnings generated by the previous statement, if any
SHOW WARNINGS;

-- Show errors from the previous statement, if any
SHOW ERRORS;

-- Show the currently selected database tables
SHOW FULL TABLES;

-- Show views
SHOW FULL TABLES
WHERE Table_type = 'VIEW';
